local colors = {
    -- content here will not be touched
    -- PATCH_OPEN
Normal = {fg = "#ffe598", bg = "#120b0d"},
FzfLuaNormal = {link = "Normal"},
LspReferenceText = {link = "Normal"},
NormalFloat = {link = "Normal"},
NormalNC = {link = "Normal"},
Pmenu = {link = "Normal"},
PmenuSbar = {link = "Normal"},
PmenuThumb = {link = "Normal"},
SignColumn = {link = "Normal"},
["@boolean"] = {link = "Boolean"},
["@character"] = {link = "Character"},
Comment = {fg = "#73655f"},
Ignore = {link = "Comment"},
LspInlayHint = {link = "Comment"},
["@comment"] = {link = "Comment"},
["@html.comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#9e333f"},
Boolean = {link = "Constant"},
["@constant"] = {link = "Constant"},
["@constant.builtin"] = {link = "Constant"},
CurSearch = {fg = "#ffe598", bg = "#807d44"},
Cursor = {fg = "#120b0d", bg = "#ffe598"},
FzfLuaCursor = {link = "Cursor"},
TermCursor = {link = "Cursor"},
CursorLine = {},
FzfLuaCursorLine = {link = "CursorLine"},
CursorLineFold = {},
CursorLineNr = {},
FzfLuaCursorLineNr = {link = "CursorLineNr"},
CursorLineSign = {},
Debug = {},
["@debug"] = {link = "Debug"},
["@constant.macro"] = {link = "Define"},
["@define"] = {link = "Define"},
Delimiter = {fg = "#ffe598"},
["@punctuation.bracket"] = {link = "Delimiter"},
DiagnosticError = {fg = "#9e333f"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#73655f"},
DiagnosticFloatingHint = {link = "DiagnosticHint"},
DiagnosticSignHint = {link = "DiagnosticHint"},
DiagnosticVirtualTextHint = {link = "DiagnosticHint"},
DiagnosticInfo = {fg = "#5D6C5A"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#928f4e"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticWarn = {fg = "#d97b36"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {fg = "#807d44"},
DiffChange = {fg = "#73655f"},
DiffDelete = {fg = "#9e333f"},
DiffText = {},
Directory = {fg = "#807d44"},
EndOfBuffer = {fg = "#5D514C"},
Error = {fg = "#9e333f"},
ErrorMsg = {fg = "#d97b36"},
["@exception"] = {link = "Exception"},
Field = {fg = "#476746"},
["@field"] = {link = "Field"},
["@property"] = {link = "Field"},
["@float"] = {link = "Float"},
FloatBorder = {fg = "#476746"},
FloatTitle = {fg = "#928f4e"},
Function = {fg = "#807d44"},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
FzfLuaBorder = {fg = "#928f4e"},
FzfLuaTitle = {fg = "#476746"},
GitSignsAdd = {fg = "#807d44"},
GitSignsChange = {fg = "#6a5f3f"},
GitSignsDelete = {fg = "#d97b36"},
IblIndent = {fg = "#151E15", nocombine = true},
IblScope = {fg = "#4D4B28", nocombine = true},
IblWhitespace = {fg = "#151E15", nocombine = true},
Identifier = {fg = "#ffe598"},
["@lsp.type.parameter"] = {link = "Identifier"},
["@lsp.type.property"] = {link = "Identifier"},
["@lsp.type.variable"] = {link = "Identifier"},
["@namespace"] = {link = "Identifier"},
["@parameter"] = {link = "Identifier"},
["@property.lua"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
IncSearch = {fg = "#ffe598", bg = "#d9b054"},
FzfLuaSearch = {link = "IncSearch"},
Substitute = {link = "IncSearch"},
["@include"] = {link = "Include"},
Keyword = {fg = "#928f4e"},
Statement = {link = "Keyword"},
["@keyword"] = {link = "Keyword"},
["@label"] = {link = "Label"},
LineNr = {fg = "#807d44"},
LineNrAbove = {fg = "#73655f"},
LineNrBelow = {fg = "#73655f"},
LspCodeLens = {},
LspCodeLensSeparator = {},
LspReferenceRead = {},
LspReferenceWrite = {},
LspSignatureActiveParameter = {},
["@function.macro"] = {link = "Macro"},
["@macro"] = {link = "Macro"},
MatchParen = {},
MiniTablineHidden = {bg = "#362127"},
MiniTablineVisible = {link = "MiniTablineHidden"},
MiniTablineModifiedCurrent = {bg = "#5D6C5A", bold = true},
MiniTablineModifiedHidden = {fg = "#d9b054", bg = "#362127"},
MiniTablineModifiedVisible = {link = "MiniTablineModifiedHidden"},
ModeMsg = {},
MoreMsg = {},
MsgArea = {},
MsgSeparator = {},
NonText = {},
Number = {fg = "#9e333f"},
Float = {link = "Number"},
["@number"] = {link = "Number"},
Operator = {fg = "#5D6C5A"},
["@markup.list"] = {link = "Operator"},
["@operator"] = {link = "Operator"},
PmenuExtra = {link = "Pmenu"},
PmenuExtraSel = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
FzfLuaScrollFloatEmpty = {link = "PmenuSbar"},
PmenuSel = {fg = "#ffe598", bg = "#928f4e"},
PmenuKindSel = {link = "PmenuSel"},
FzfLuaScrollFloatFull = {link = "PmenuThumb"},
PreProc = {fg = "#5D6C5A"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
["@punctuation.special.rust"] = {link = "PreProc"},
Question = {},
QuickFixLine = {},
["@repeat"] = {link = "Repeat"},
Search = {fg = "#ffe598", bg = "#9e333f"},
Special = {fg = "#d97b36"},
SpecialChar = {link = "Special"},
Tag = {link = "Special"},
["@constructor"] = {link = "Special"},
["@marup.raw.block.markdown"] = {link = "Special"},
["@tag.html"] = {link = "Special"},
["@string.escape"] = {link = "SpecialChar"},
["@string.special"] = {link = "SpecialChar"},
SpecialComment = {},
["@character.special"] = {link = "SpecialComment"},
SpecialKey = {},
SpellBad = {},
SpellCap = {},
SpellLocal = {},
SpellRare = {},
Conditional = {link = "Statement"},
Exception = {link = "Statement"},
Label = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {bg = "#160E10"},
StatusLineNC = {link = "StatusLine"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#d9b054"},
Character = {link = "String"},
["@string"] = {link = "String"},
TabLine = {bg = "#2F2327"},
TabLineFill = {fg = "#ffe598", bg = "#120b0d"},
TabLineSel = {bg = "#807d44", bold = true},
MiniTablineCurrent = {link = "TabLineSel"},
TabLineSelSep = {fg = "#807d44", bg = "#120b0d", bold = true},
TabLineSep = {fg = "#2F2327", bg = "#120b0d"},
["@tag"] = {link = "Tag"},
Title = {fg = "#5D6C5A"},
["@markup.heading"] = {link = "Title"},
["@text.title"] = {link = "Title"},
Todo = {},
["@text.todo"] = {link = "Todo"},
Type = {fg = "#d97b36"},
StorageClass = {link = "Type"},
Typedef = {link = "Type"},
["@structure"] = {link = "Type"},
["@type"] = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
DiagnosticUnderlineError = {link = "Underlined"},
DiagnosticUnderlineHint = {link = "Underlined"},
DiagnosticUnderlineInfo = {link = "Underlined"},
DiagnosticUnderlineOk = {link = "Underlined"},
DiagnosticUnderlineWarn = {link = "Underlined"},
["@text.underline"] = {link = "Underlined"},
["@text.uri"] = {link = "Underlined"},
Visual = {bg = "#2F2327"},
VisualNOS = {},
WarningMsg = {},
Whitespace = {},
WildMenu = {},
WinBar = {},
WinBarNC = {},
Winseparator = {},
markdownBold = {bold = true},
markdownItalic = {italic = true},
["@constructor.lua"] = {fg = "#c16e31"},
["@function.builtin"] = {fg = "#d97b36"},
["@lsp.type.derive"] = {fg = "#476746"},
["@markup.link"] = {fg = "#77824A"},
["@punctuation"] = {fg = "#6a5f3f"},
["@type.builtin"] = {fg = "#5D6C5A"},
    -- PATCH_CLOSE
    -- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='monalisa'")

-- apply highlight groups
for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end
